/**
 * CATALOG.md 생성기 — T1~T8 + AXDD Extension 그루핑.
 *
 * AxDD-SKILLS reference의 CATALOG.md 형식과 정합.
 */

import type { Skill, SkillCategory } from "./types";

interface CatalogGroup {
  tType: string;
  label: string;
  description: string;
  skills: Skill[];
}

const CATEGORY_TO_GROUP: Record<
  SkillCategory,
  { tType: string; label: string; description: string }
> = {
  simple: {
    tType: "T1",
    label: "Minimal SOP",
    description: "한 페이지 분량의 SOP. references/scripts/assets 없이 SKILL.md만.",
  },
  reference: {
    tType: "T2",
    label: "Reference-heavy",
    description: "도메인 코퍼스(스타일 가이드·용어집 등)를 progressive disclosure로 참조.",
  },
  script: {
    tType: "T3",
    label: "Script-backed",
    description: "결정적 계산·변환을 위한 stdlib Python 등 외부 스크립트 호출.",
  },
  "asset-template": {
    tType: "T4",
    label: "Asset-template",
    description: "정형 산출물 (PR 설명·보고서 등). 캐노니컬 템플릿 asset 사용.",
  },
  "full-step": {
    tType: "T5",
    label: "Full-stack",
    description: "scripts + references + assets 풀 파이프라인.",
  },
  "meta-tooling": {
    tType: "T6",
    label: "Meta / Tooling",
    description: "다른 스킬을 만들거나 검증·관리하는 메타 스킬.",
  },
  integration: {
    tType: "T7",
    label: "API / Integration",
    description: "외부 HTTP 서비스 호출 (인증·페이지네이션·rate limit 포함).",
  },
  "frontmatter-overlay": {
    tType: "T8",
    label: "Optional Frontmatter",
    description: "license/compatibility/metadata/allowed-tools 등 선택 필드 오버레이.",
  },
  validation: {
    tType: "AXDD-ext",
    label: "Validation (AXDD Extension)",
    description: "AXDD 확장 — 산출물 검증·체크리스트 전용 스킬. T1~T8 외.",
  },
};

const T_ORDER: SkillCategory[] = [
  "simple",
  "reference",
  "script",
  "asset-template",
  "full-step",
  "meta-tooling",
  "integration",
  "frontmatter-overlay",
  "validation",
];

export interface WorkUnitForCatalog {
  id: string;
  name: string;
  requiredSkills: string[];
}

/**
 * Root CATALOG.md 생성. T1~T8 그루핑 + AXDD Extensions + Work Units 섹션 포함.
 */
export function buildRootCatalog(
  skills: Skill[],
  workUnits: WorkUnitForCatalog[] = [],
): string {
  // 그룹별로 분류
  const groups = new Map<SkillCategory, Skill[]>();
  for (const s of skills) {
    if (!groups.has(s.category)) groups.set(s.category, []);
    groups.get(s.category)!.push(s);
  }

  const lines: string[] = [
    "# AXDD Skills Catalog",
    "",
    "> AxDD-SKILLS reference 호환 카탈로그.",
    "> 분류: T1~T8 (Composite taxonomy) + AXDD Extensions.",
    "> 폴더는 flat — T-type은 폴더 nesting이 아니라 본 카탈로그에서 분류한다.",
    "",
    "## Index",
    "",
    "| Skill | T-Type | Path | Status |",
    "|-------|--------|------|--------|",
  ];

  // Index — 모든 스킬 한 줄씩 (Phase 7-F: Enterprise Export 시점은 모두 Draft)
  const allSkillsForIndex = T_ORDER.flatMap((cat) => groups.get(cat) ?? []);
  for (const s of allSkillsForIndex) {
    const grp = CATEGORY_TO_GROUP[s.category];
    lines.push(
      `| ${s.name} | ${grp.tType} | [skills/${s.id}](skills/${s.id}/SKILL.md) | Draft |`,
    );
  }

  // T1~T8 + AXDD Extension 각 섹션 — Phase 7-F: 빈 섹션도 모두 표시 (taxonomy 명시)
  for (const cat of T_ORDER) {
    const list = groups.get(cat) ?? [];
    const grp = CATEGORY_TO_GROUP[cat];
    lines.push("");
    lines.push(`## ${grp.tType} — ${grp.label}`);
    lines.push("");
    lines.push(`> ${grp.description}`);
    lines.push("");

    if (list.length === 0) {
      lines.push("_No generated skills in this export._");
      continue;
    }

    lines.push("| Skill | Path | Purpose |");
    lines.push("|-------|------|---------|");
    for (const s of list) {
      lines.push(
        `| ${s.name} | \`skills/${s.id}/\` | ${escapePipe(s.description)} |`,
      );
    }
  }

  // Work Units 섹션
  if (workUnits.length > 0) {
    lines.push("");
    lines.push("## Work Units (Composite Kits)");
    lines.push("");
    lines.push(
      "> 여러 atomic skill을 묶어 실제 업무 흐름을 만드는 composition.",
    );
    lines.push("");
    lines.push("| Work Unit | Path | Required Skills |");
    lines.push("|-----------|------|-----------------|");
    for (const wu of workUnits) {
      lines.push(
        `| ${wu.name} | \`work-units/${wu.id}/\` | ${wu.requiredSkills.length} skills |`,
      );
    }
  }

  // Validation
  lines.push("");
  lines.push("## Validation");
  lines.push("");
  lines.push("```bash");
  lines.push("# 모든 스킬 frontmatter / 디렉토리명 일치 / secret 패턴 검사");
  lines.push(
    "for d in skills/*; do python3 validation/axe_check.py validate-skill \"$d\"; done",
  );
  lines.push("");
  lines.push("# 모든 work-unit 정의 검증");
  lines.push(
    "for d in work-units/*; do python3 validation/axe_check.py validate-workunit \"$d\"; done",
  );
  lines.push("```");
  lines.push("");
  lines.push("---");
  lines.push("Generated by AXDD SkillOps Console — Enterprise Export.");

  return lines.join("\n");
}

function escapePipe(s: string): string {
  return s.replace(/\|/g, "\\|");
}
